import { useState, useRef } from 'react'
import { decodeImage } from '../utils/decode'

/**
 * Decode page — lets the user upload a stego image and a password to
 * extract and download the hidden file.
 */
function Decode() {
  const [image,      setImage]      = useState(null)
  const [password,   setPassword]   = useState('')
  const [outputFile, setOutputFile] = useState(null)   // { url, name }
  const [loading,    setLoading]    = useState(false)

  const canvasRef    = useRef()
  const imageInputRef = useRef()

  // ── Helpers ────────────────────────────────────────────────────────────────

  /**
   * Sets the selected image and clears any previous decode result.
   * @param {File} file
   */
  const selectImage = (file) => {
    if (!file.type.startsWith('image/')) {
      alert('Please upload a valid image file.')
      return
    }
    setImage(file)
    setOutputFile(null)
  }

  const handleDrop     = (e) => { e.preventDefault(); selectImage(e.dataTransfer.files[0]) }
  const handleDragOver = (e) => e.preventDefault()

  // ── Decode ─────────────────────────────────────────────────────────────────

  /**
   * Loads the stego image, then calls decodeImage to extract,
   * decrypt, and decompress the hidden file.
   */
  const handleDecode = () => {
    if (!image)    { alert('Please upload a stego image.');         return }
    if (!password) { alert('Please enter the decryption password.'); return }

    setLoading(true)
    setOutputFile(null)

    const objectUrl = URL.createObjectURL(image)
    const img = new window.Image()
    img.src = objectUrl

    img.onload = async () => {
      try {
        const { blob, fileName } = await decodeImage(img, canvasRef.current, password)
        setOutputFile({ url: URL.createObjectURL(blob), name: fileName })
      } catch (err) {
        alert(err.message)
      } finally {
        setLoading(false)
        URL.revokeObjectURL(objectUrl)
      }
    }

    img.onerror = () => {
      alert('Failed to load image. Ensure it is a valid image file.')
      setLoading(false)
      URL.revokeObjectURL(objectUrl)
    }
  }

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="decode-container container py-5">

      {/* Page header */}
      <div className="text-center text-white mb-4">
        <h1>Decode Data from Image</h1>
        <p>Extract hidden data from a steganographic image</p>
      </div>

      <div className="row g-4">

        {/* Stego image drop zone */}
        <div className="col-md-8 offset-md-2">
          <label className="label-text">Stego Image</label>
          <div
            className="drop-zone"
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onClick={() => imageInputRef.current.click()}
          >
            <p className="mb-0">Select or drop stego image</p>
            {image && <span className="file-name">{image.name}</span>}
            <input
              type="file"
              accept="image/*"
              hidden
              ref={imageInputRef}
              onChange={(e) => selectImage(e.target.files[0])}
            />
          </div>
        </div>

        {/* Password field */}
        <div className="col-md-8 offset-md-2">
          <label className="label-text">Decryption Password</label>
          <input
            type="password"
            className="form-control custom-input"
            placeholder="Enter password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>

        {/* Decode button */}
        <div className="col-12 text-center">
          <button
            className="primary-btn"
            onClick={handleDecode}
            disabled={loading}
          >
            {loading && <span className="spinner-border spinner-border-sm me-2" />}
            {loading ? 'Decoding…' : 'Execute Decoding'}
          </button>
        </div>

        {/* Output — shown after successful extraction */}
        {outputFile && (
          <div className="col-12 text-center mt-4">
            <div className="output-box">
              <h5>File Extracted Successfully</h5>
              <p>{outputFile.name}</p>
              <a href={outputFile.url} download={outputFile.name} className="primary-btn">
                Download File
              </a>
            </div>
          </div>
        )}

      </div>

      {/* Hidden canvas used by the steganography engine */}
      <canvas ref={canvasRef} style={{ display: 'none' }} />

      {/* Instructions */}
      <div className="info-box mt-5">
        <h5>⚠️ Please read before decoding</h5>
        <ul>
          <li>Upload the stego image that was generated by this encoder.</li>
          <li>Supported formats: PNG or BMP (lossless only).</li>
          <li>If you received a ZIP file, extract it first, then upload the image inside.</li>
          <li>Enter the exact password used during encoding.</li>
          <li>A wrong password will produce corrupted or no output.</li>
          <li>If no data is found, the image may not be encoded or the data was destroyed.</li>
          <li>Avoid images shared via WhatsApp or social media — compression removes hidden data.</li>
          <li>Always use the original PNG or the ZIP version for reliable results.</li>
        </ul>
      </div>

    </div>
  )
}

export default Decode